name: Test Default

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
    name: 👷 CI on ${{ matrix.os }}

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Environment
        uses: ./
        with:
          cwd: ./labs

  test-runtime:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        runtime: [node, deno, bun]
        experimental: [false]
    name: 👷 CI ${{ matrix.runtime }} on ${{ matrix.os }}

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: 🔥 Remove lockfile
        run: rm ./labs/pnpm-lock.yaml

      - name: Setup Test Environment
        uses: ./
        with:
          runtime: ${{ matrix.runtime }}
          cwd: ./labs
