name: Test

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        runtime: [node, deno, bun]
        version: ["latest"]
        pm: [npm, pnpm, yarn]
        exclude:
          - runtime: bun
            pm: pnpm
          - runtime: bun
            pm: yarn
          - runtime: deno
            pm: pnpm
          - runtime: deno
            pm: yarn
    name: 👷 CI ${{ matrix.runtime }}@${{ matrix.version }} under ${{ matrix.os }} using ${{ matrix.pm }}

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Environment
        uses: ./
        with:
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix.version }}
          pm: ${{ matrix.pm }}
          scripts: check,test
