name: Test Default

on: ['push', 'pull_request']

jobs:
  test-lockfile:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
    name: 👷 CI on ${{ matrix.os }}

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Environment
        uses: ./

  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
    name: 👷 CI on ${{ matrix.os }} without lockfile

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: 🔥 Remove lockfile
        run: rm pnpm-lock.yaml

      - name: Setup Test Environment
        uses: ./
